apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-es
  template:
    metadata:
      labels:
        app: my-app-es
    spec:
      containers:
        - name: my-app-es
          image: my-app-es:latest
          ports:
            - containerPort: 80
