apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-es
  template:
    metadata:
      labels:
        app: flask-app-es
    spec:
      containers:
        - name: flask-app-es
          image: edwinasweeney/flaskapp:v1
          ports:
            - containerPort: 80
