apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
sp
  project: default

  source:
    repoURL: https://github.com/e-sweeney/Student-Performance.git
    targetRevision: main
    path: k8s   # 👈 folder in your repo containing manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true