name: Dosomething
on:
    workflow_dispatch:
    

  

jobs:
    job-name:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6
            - name: Printing Folders
              run:
                ls
         
      
